name: Update Trailhead Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  trailhead-stats:
    name: Trailhead Stats
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Trailhead stats
        id: trailhead-stats
        uses: nabondance/Trailhead-Stats@main
        with:
          trailhead-username: abhishakec
          display-file: 'README.md'
          file-format: 'html'
          card-path: './TS-cards'
          dark-style: 'dark'
          display-type: 'card'
          show-skill: 'hidden'
          show-certification: 'hidden'
          show-badge: 'hidden'
          show-superbadge: 'hidden'
          show-event-badge: 'hidden'
          show-stamp: 'hidden'
          show-certification-latest: 'hidden'
          show-badge-latest: 'hidden'
          show-superbadge-latest: 'visible'
          show-event-badge-latest: 'hidden'
          show-stamp-latest: 'hidden'
